### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by 4dvn** [ALinck/JPEG-header-repair#1]
the code not working

**Comment by ALinck** [comment]
This was some of the first code I ever wrote. It worked back when I wrote it, but it will take some time to go over it and get it working again.

**Comment by ALinck** [comment]
Ran it using Python 3.8 and it still works. What issue were you having?

**Comment by 4dvn** [comment]
> Ran it using Python 3.8 and it still works. What issue were you having?

Thank you for reply, Can you upload the corrupt image sample? When i run it some chinese show, my image is corrupt 150kb of header

**Comment by ALinck** [comment]
![bbyoda](https://user-images.githubusercontent.com/3385236/78322607-3f14bd00-753d-11ea-9ccd-812e8c7c4c53.jpg)

**Comment by 4dvn** [comment]
![IMG_4312_](https://user-images.githubusercontent.com/46510477/78323699-d5c49680-759c-11ea-83c3-18d5f98ba88c.JPG)
here is my corrupt jpeg of 150kb of header but i don't know how to fix it

**Comment by ALinck** [comment]
I see. The bits marking the start of the file (FF D8) are fine and at the beginning of the file. There could be some corruption further into the header. I also don't see the expected EOF marker (FF D9) at the end of the file.

**Comment by ALinck** [comment]
Code not designed to fix this issue.
